### PR TITLE
throw when facet is missing data

### LINKED ISSUE #371: Better error message for unspecified facet data
A plot call like this

```js
Plot.lineY(data, {
  x: 'year',
  y: 'employ_n'
}).plot({ facet: { x: 'major_occupation', y: 'minor_occupation' } })
```

Currently gives the error `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`. What this actually means is that the `facet` specification wants to be passed a `data` array:

```js
Plot.lineY(data, {
  x: 'year',
  y: 'employ_n'
}).plot({ facet: { data: data, x: 'major_occupation', y: 'minor_occupation' } })
```

Perhaps the error could be more clear on this point, e.g. something along the lines of `Error: Faceting requires 'data' to be specified in the plot facet options.`

### PR DESCRIPTION
**Pull request by Fil**
closes #371

### CODE REVIEW

File: src/facet.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ export function facets(data, {x, y, ...options}, marks) {
 
 class Facet extends Mark {
   constructor(data, {x, y, ...options} = {}, marks = []) {
+    if (data === undefined) throw "Missing facet data";
```
Comment (mbostock) [inline src/facet.js:13]:
```suggestion
    if (data === undefined) throw Error("missing facet data");
```

**Comment by mbostock** [comment]
I’m not sure this is the right fix. My intent was that if you don’t specify the facet data, it’s equivalent to not having faceting—not that your Plot now throws an error. I think there’s a different error at play here perhaps?

**Comment by Fil** [comment]
The bug is that Plot crashes when there is a facet with no (iterable) data attribute. Both approaches (error or ignore) can be valid fixes for that bug.

Now, a common difficulty I've experienced and seen people struggle with is that when you focus on faceting and you are working on one dataset, you will naturally write  `facet: {x: "key"}` and forget to add `data`. A second difficulty is that when you start from an example that is written `facet: {data, x: "key"}` and yo want to substitute your own dataset, you will tend to replace `data` by the new dataset, and do `facet: {penguins, x: "key"}`.

With the "ignore" proposal, these two do nothing and leave you wondering why. With the "error" proposal they give you a reason. "error" has my preference.

Writing this I realize that we could error if data is undefined, and ignore if it is null or false (ie explicitely disabled).

(Currently, to disable faceting  temporarily I rename `facet` to `_facet`.)

**Review by mbostock — APPROVED** [review]
