### PR TITLE
spaces are not numbers

### LINKED ISSUE #1056: a space is interpreted as a number
`Plot.plot({ marks: [Plot.barX([{ x: 200, y: " " }], { x: "x", y: "y" })] })` wrongly recognizes the space as a number, then warns about y being numbers.

### PR DESCRIPTION
**Pull request by Fil**
closes #1056

(includes #1059)

### CODE REVIEW

File: src/options.js [hunk 1]
```diff
@@ -331,7 +331,7 @@ export function isTemporalString(values) {
 export function isNumericString(values) {
   for (const value of values) {
     if (value == null || value === "") continue;
```
Comment (mbostock) [inline src/options.js:333]: Given that we already ignore the empty string, I wonder if we shouldn’t ignore all whitespace strings, too?

```suggestion
    if (value == null || (typeof value === "string" && /^\s*$/.test(value))) continue;
```

Then you won’t need to trim below, and it would mean that we continue checking the other values if we encounter a whitespace string (rather than returning false).

**Review by mbostock — CHANGES_REQUESTED** [review]

**Review by mbostock — APPROVED** [review]
Added tests and simplified.
